<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.3.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogicModule\BusinessLogicModule.csproj" />
    <ProjectReference Include="..\ConfigurationModule\ConfigurationModule.csproj" />
    <ProjectReference Include="..\ConnectionModule\ConnectionModule.csproj" />
    <ProjectReference Include="..\ConverterModule\ConverterModule.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\LoggingModule\LoggingModule.csproj" />
  </ItemGroup>

</Project>
