// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GuidanceHost.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DriveToParkPositionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Drive To Park Position", "  The Drive To Park Position screen is step 5 of the GuidanceUI.\r\n  It presents 4" +
                " numbered instructions the operator must follow before installation,\r\n  then let" +
                "s them Proceed (advance to Installation) or Cancel (send CloseApp).", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "DriveToParkPosition.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the app is running and the drive to park position screen is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DriveToParkPosition.feature.ndjson", 18);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Drive to Park Position screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Drive to Park Position screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-A01")]
        public async global::System.Threading.Tasks.Task DriveToParkPositionScreenIsVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "DTP-A01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Drive to Park Position screen is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.ThenAsync("the element \"drive-to-park-position-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-B02")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B02", "driveToPark.title", "1", null, DisplayName="Screen displays the correct static text(DTP-B02,driveToPark.title,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B03", "driveToPark.step1", "2", null, DisplayName="Screen displays the correct static text(DTP-B03,driveToPark.step1,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B04", "driveToPark.step2", "3", null, DisplayName="Screen displays the correct static text(DTP-B04,driveToPark.step2,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B05", "driveToPark.step3", "4", null, DisplayName="Screen displays the correct static text(DTP-B05,driveToPark.step3,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B06", "driveToPark.step4", "5", null, DisplayName="Screen displays the correct static text(DTP-B06,driveToPark.step4,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B07", "driveToPark.info", "6", null, DisplayName="Screen displays the correct static text(DTP-B07,driveToPark.info,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-B08", "common.copyright", "7", null, DisplayName="Screen displays the correct static text(DTP-B08,common.copyright,7)")]
        public async global::System.Threading.Tasks.Task ScreenDisplaysTheCorrectStaticText(string tag, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DTP-B02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Screen displays the correct static text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.ThenAsync(string.Format("the element \"drive-to-park-position-screen\" contains i18n text \"{0}\"", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons are visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons are visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-C09")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C09", "proceed-btn", "8", null, DisplayName="Action buttons are visible(DTP-C09,proceed-btn,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C10", "cancel-btn", "9", null, DisplayName="Action buttons are visible(DTP-C10,cancel-btn,9)")]
        public async global::System.Threading.Tasks.Task ActionButtonsAreVisible(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DTP-C09"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons are visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.ThenAsync(string.Format("the element \"{0}\" is visible", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons have the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons have the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-C11")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C11", "proceed-btn", "primary", "10", null, DisplayName="Action buttons have the correct color(DTP-C11,proceed-btn,primary,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C12", "cancel-btn", "secondary", "11", null, DisplayName="Action buttons have the correct color(DTP-C12,cancel-btn,secondary,11)")]
        public async global::System.Threading.Tasks.Task ActionButtonsHaveTheCorrectColor(string tag, string element, string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DTP-C11"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons have the correct color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"color\" equal to \"{1}\"", element, color), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons display the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons display the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-C13")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C13", "proceed-btn", "common.proceed", "12", null, DisplayName="Action buttons display the correct label(DTP-C13,proceed-btn,common.proceed,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("DTP-C14", "cancel-btn", "common.cancel", "13", null, DisplayName="Action buttons display the correct label(DTP-C14,cancel-btn,common.cancel,13)")]
        public async global::System.Threading.Tasks.Task ActionButtonsDisplayTheCorrectLabel(string tag, string element, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DTP-C13"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons display the correct label", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"label\" equal to i18n key \"{1}\"", element, key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Info-bar hint displays the correct text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Info-bar hint displays the correct text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-D15")]
        public async global::System.Threading.Tasks.Task Info_BarHintDisplaysTheCorrectText()
        {
            string[] tagsOfScenario = new string[] {
                    "DTP-D15"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Info-bar hint displays the correct text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
    await testRunner.ThenAsync("the element \"drive-to-park-info-bar-hint\" has attribute \"label\" equal to i18n key" +
                        " \"driveToPark.info\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Clicking Proceed navigates to the Installation screen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Clicking Proceed navigates to the Installation screen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Drive To Park Position")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DTP-E16")]
        public async global::System.Threading.Tasks.Task ClickingProceedNavigatesToTheInstallationScreen()
        {
            string[] tagsOfScenario = new string[] {
                    "DTP-E16"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking Proceed navigates to the Installation screen", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
    await testRunner.WhenAsync("the element \"proceed-btn\" is clicked", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the element \"installation-in-progress-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
