// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GuidanceHost.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class SavePatientImagesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Save Patient Images", "  The Save Patient Images screen is step 4 of the GuidanceUI.\r\n  It instructs the" +
                " user to archive or export patient images before installation begins,\r\n  then le" +
                "ts them Proceed (advance to Drive to Park Position) or Cancel (send CloseApp).", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "SavePatientImages.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the app is running and the save patient images screen is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/SavePatientImages.feature.ndjson", 15);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Save Patient Images screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save Patient Images screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-A01")]
        public async global::System.Threading.Tasks.Task SavePatientImagesScreenIsVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "SPI-A01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Save Patient Images screen is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.ThenAsync("the element \"save-patient-images-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-B02")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-B02", "savePatientImages.title", "1", null, DisplayName="Screen displays the correct static text(SPI-B02,savePatientImages.title,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-B03", "savePatientImages.description", "2", null, DisplayName="Screen displays the correct static text(SPI-B03,savePatientImages.description,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-B04", "savePatientImages.info", "3", null, DisplayName="Screen displays the correct static text(SPI-B04,savePatientImages.info,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-B05", "common.copyright", "4", null, DisplayName="Screen displays the correct static text(SPI-B05,common.copyright,4)")]
        public async global::System.Threading.Tasks.Task ScreenDisplaysTheCorrectStaticText(string tag, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SPI-B02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Screen displays the correct static text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.ThenAsync(string.Format("the element \"save-patient-images-screen\" contains i18n text \"{0}\"", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons are visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons are visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-C06")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C06", "proceed-btn", "5", null, DisplayName="Action buttons are visible(SPI-C06,proceed-btn,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C07", "cancel-btn", "6", null, DisplayName="Action buttons are visible(SPI-C07,cancel-btn,6)")]
        public async global::System.Threading.Tasks.Task ActionButtonsAreVisible(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SPI-C06"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons are visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.ThenAsync(string.Format("the element \"{0}\" is visible", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons have the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons have the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-C08")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C08", "proceed-btn", "primary", "7", null, DisplayName="Action buttons have the correct color(SPI-C08,proceed-btn,primary,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C09", "cancel-btn", "secondary", "8", null, DisplayName="Action buttons have the correct color(SPI-C09,cancel-btn,secondary,8)")]
        public async global::System.Threading.Tasks.Task ActionButtonsHaveTheCorrectColor(string tag, string element, string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SPI-C08"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons have the correct color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"color\" equal to \"{1}\"", element, color), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Action buttons display the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Action buttons display the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-C10")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C10", "proceed-btn", "common.proceed", "9", null, DisplayName="Action buttons display the correct label(SPI-C10,proceed-btn,common.proceed,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("SPI-C11", "cancel-btn", "common.cancel", "10", null, DisplayName="Action buttons display the correct label(SPI-C11,cancel-btn,common.cancel,10)")]
        public async global::System.Threading.Tasks.Task ActionButtonsDisplayTheCorrectLabel(string tag, string element, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SPI-C10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Action buttons display the correct label", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 50
    await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"label\" equal to i18n key \"{1}\"", element, key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Info-bar hint displays the correct text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Info-bar hint displays the correct text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-D12")]
        public async global::System.Threading.Tasks.Task Info_BarHintDisplaysTheCorrectText()
        {
            string[] tagsOfScenario = new string[] {
                    "SPI-D12"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Info-bar hint displays the correct text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 61
    await testRunner.ThenAsync("the element \"save-patient-images-info-bar-hint\" has attribute \"label\" equal to i1" +
                        "8n key \"savePatientImages.info\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Clicking Proceed navigates to the Drive to Park Position screen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Clicking Proceed navigates to the Drive to Park Position screen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SPI-E13")]
        public async global::System.Threading.Tasks.Task ClickingProceedNavigatesToTheDriveToParkPositionScreen()
        {
            string[] tagsOfScenario = new string[] {
                    "SPI-E13"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clicking Proceed navigates to the Drive to Park Position screen", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 67
    await testRunner.WhenAsync("the element \"proceed-btn\" is clicked", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
    await testRunner.ThenAsync("the element \"drive-to-park-position-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
