// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace GuidanceHost.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class VerificationResultFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Verification Result", @"  The Verification Result screen is step 3 of the GuidanceUI.
  It is reached automatically after the WPF backend responds to the
  VerifyInstallationPrerequisite command and Angular auto-navigates here.
  The screen renders two entirely different layouts depending on whether the
  backend sent Status=""OK"" (prereqOk=true) or Status=""Not Ok"" (prereqOk=false).
  Both paths are tested here; each suite requires the WPF host to be configured
  with the matching DefaultPrerequisiteStatus value in MainWindow.xaml.cs.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "VerificationResult.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/VerificationResult.feature.ndjson", 39);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-01 — Verification Result screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-01 — Verification Result screen is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-A01")]
        public async global::System.Threading.Tasks.Task VRS_01VerificationResultScreenIsVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "VRS-A01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-01 — Verification Result screen is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
      await testRunner.ThenAsync("the element \"verification-result-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Screen displays the correct static text")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-B02")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("02", "verificationResult.title", "1", null, DisplayName="VRS-<tag> — Screen displays the correct static text(02,verificationResult.title,1" +
            ")")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("03", "verificationResult.success.subtitle", "2", null, DisplayName="VRS-<tag> — Screen displays the correct static text(03,verificationResult.success" +
            ".subtitle,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("04", "verificationResult.success.body", "3", null, DisplayName="VRS-<tag> — Screen displays the correct static text(04,verificationResult.success" +
            ".body,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("05", "verificationResult.success.info", "4", null, DisplayName="VRS-<tag> — Screen displays the correct static text(05,verificationResult.success" +
            ".info,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("06", "common.copyright", "5", null, DisplayName="VRS-<tag> — Screen displays the correct static text(06,common.copyright,5)")]
        public async global::System.Threading.Tasks.Task VRS_TagScreenDisplaysTheCorrectStaticText(string tag, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-B02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Screen displays the correct static text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
      await testRunner.ThenAsync(string.Format("the element \"verification-result-screen\" contains i18n text \"{0}\"", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-07 — Result status notification is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-07 — Result status notification is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-C07")]
        public async global::System.Threading.Tasks.Task VRS_07ResultStatusNotificationIsVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "VRS-C07"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-07 — Result status notification is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
      await testRunner.ThenAsync("the element \"result-status\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Result status notification has the correct attribute")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Result status notification has the correct attribute")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-C08")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("08", "type", "success", "7", null, DisplayName="VRS-<tag> — Result status notification has the correct attribute(08,type,success," +
            "7)")]
        public async global::System.Threading.Tasks.Task VRS_TagResultStatusNotificationHasTheCorrectAttribute(string tag, string attribute, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-C08"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("attribute", attribute);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Result status notification has the correct attribute", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
      await testRunner.ThenAsync(string.Format("the element \"result-status\" has attribute \"{0}\" equal to \"{1}\"", attribute, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-09 — Result status notification label matches i18n key")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-09 — Result status notification label matches i18n key")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-C09")]
        public async global::System.Threading.Tasks.Task VRS_09ResultStatusNotificationLabelMatchesI18NKey()
        {
            string[] tagsOfScenario = new string[] {
                    "VRS-C09"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-09 — Result status notification label matches i18n key", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 54
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
      await testRunner.ThenAsync("the element \"result-status\" has attribute \"label\" equal to i18n key \"verification" +
                        "Result.success.title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Success-path button is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Success-path button is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-D10")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10", "cancel-btn", "9", null, DisplayName="VRS-<tag> — Success-path button is visible(10,cancel-btn,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("11", "proceed-install-btn", "10", null, DisplayName="VRS-<tag> — Success-path button is visible(11,proceed-install-btn,10)")]
        public async global::System.Threading.Tasks.Task VRS_TagSuccess_PathButtonIsVisible(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-D10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Success-path button is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 60
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
      await testRunner.ThenAsync(string.Format("the element \"{0}\" is visible", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Success-path button has the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Success-path button has the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-D12")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("12", "cancel-btn", "secondary", "11", null, DisplayName="VRS-<tag> — Success-path button has the correct color(12,cancel-btn,secondary,11)" +
            "")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("13", "proceed-install-btn", "primary", "12", null, DisplayName="VRS-<tag> — Success-path button has the correct color(13,proceed-install-btn,prim" +
            "ary,12)")]
        public async global::System.Threading.Tasks.Task VRS_TagSuccess_PathButtonHasTheCorrectColor(string tag, string element, string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-D12"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Success-path button has the correct color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
      await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"color\" equal to \"{1}\"", element, color), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Success-path button has the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Success-path button has the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-D14")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("14", "cancel-btn", "common.cancel", "13", null, DisplayName="VRS-<tag> — Success-path button has the correct label(14,cancel-btn,common.cancel" +
            ",13)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("15", "proceed-install-btn", "verificationResult.success.proceedInstall", "14", null, DisplayName="VRS-<tag> — Success-path button has the correct label(15,proceed-install-btn,veri" +
            "ficationResult.success.proceedInstall,14)")]
        public async global::System.Threading.Tasks.Task VRS_TagSuccess_PathButtonHasTheCorrectLabel(string tag, string element, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-D14"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Success-path button has the correct label", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
      await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"label\" equal to i18n key \"{1}\"", element, key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-<tag> — Error-path button is not present on the success path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-<tag> — Error-path button is not present on the success path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-E16")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("16", "show-report-btn", "15", null, DisplayName="VRS-<tag> — Error-path button is not present on the success path(16,show-report-b" +
            "tn,15)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("17", "ok-btn", "16", null, DisplayName="VRS-<tag> — Error-path button is not present on the success path(17,ok-btn,16)")]
        public async global::System.Threading.Tasks.Task VRS_TagError_PathButtonIsNotPresentOnTheSuccessPath(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRS-E16"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-<tag> — Error-path button is not present on the success path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
      await testRunner.ThenAsync(string.Format("the element \"{0}\" is not present", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-18 — Info-bar hint displays the correct text on success path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-18 — Info-bar hint displays the correct text on success path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-F18")]
        public async global::System.Threading.Tasks.Task VRS_18Info_BarHintDisplaysTheCorrectTextOnSuccessPath()
        {
            string[] tagsOfScenario = new string[] {
                    "VRS-F18"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-18 — Info-bar hint displays the correct text on success path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 100
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
      await testRunner.ThenAsync("the element \"verification-result-info-bar-hint\" has attribute \"label\" equal to i1" +
                        "8n key \"verificationResult.success.info\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRS-19 — Clicking Proceed with Installation navigates to Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRS-19 — Clicking Proceed with Installation navigates to Save Patient Images")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRS-G19")]
        public async global::System.Threading.Tasks.Task VRS_19ClickingProceedWithInstallationNavigatesToSavePatientImages()
        {
            string[] tagsOfScenario = new string[] {
                    "VRS-G19"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRS-19 — Clicking Proceed with Installation navigates to Save Patient Images", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports OK the success layout is rendered", null, tagsOfRule);
#line 106
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with a success r" +
                        "esult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
      await testRunner.WhenAsync("the element \"proceed-install-btn\" is clicked", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
      await testRunner.ThenAsync("the element \"save-patient-images-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-01 — Verification Result screen is visible on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-01 — Verification Result screen is visible on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-A01")]
        public async global::System.Threading.Tasks.Task VRE_01VerificationResultScreenIsVisibleOnErrorPath()
        {
            string[] tagsOfScenario = new string[] {
                    "VRE-A01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-01 — Verification Result screen is visible on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 123
      await testRunner.ThenAsync("the element \"verification-result-screen\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Screen displays the correct static text on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Screen displays the correct static text on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-B02")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("02", "verificationResult.title", "20", null, DisplayName="VRE-<tag> — Screen displays the correct static text on error path(02,verification" +
            "Result.title,20)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("03", "verificationResult.error.subtitle", "21", null, DisplayName="VRE-<tag> — Screen displays the correct static text on error path(03,verification" +
            "Result.error.subtitle,21)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("04", "verificationResult.error.body", "22", null, DisplayName="VRE-<tag> — Screen displays the correct static text on error path(04,verification" +
            "Result.error.body,22)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("05", "verificationResult.error.info", "23", null, DisplayName="VRE-<tag> — Screen displays the correct static text on error path(05,verification" +
            "Result.error.info,23)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("06", "common.copyright", "24", null, DisplayName="VRE-<tag> — Screen displays the correct static text on error path(06,common.copyr" +
            "ight,24)")]
        public async global::System.Threading.Tasks.Task VRE_TagScreenDisplaysTheCorrectStaticTextOnErrorPath(string tag, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-B02"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Screen displays the correct static text on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 128
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
      await testRunner.ThenAsync(string.Format("the element \"verification-result-screen\" contains i18n text \"{0}\"", key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-07 — Result status notification is visible on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-07 — Result status notification is visible on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-C07")]
        public async global::System.Threading.Tasks.Task VRE_07ResultStatusNotificationIsVisibleOnErrorPath()
        {
            string[] tagsOfScenario = new string[] {
                    "VRE-C07"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-07 — Result status notification is visible on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 142
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 143
      await testRunner.ThenAsync("the element \"result-status\" is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Result status notification has the correct attribute on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Result status notification has the correct attribute on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-C08")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("08", "type", "error", "26", null, DisplayName="VRE-<tag> — Result status notification has the correct attribute on error path(08" +
            ",type,error,26)")]
        public async global::System.Threading.Tasks.Task VRE_TagResultStatusNotificationHasTheCorrectAttributeOnErrorPath(string tag, string attribute, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-C08"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("attribute", attribute);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Result status notification has the correct attribute on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 146
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
      await testRunner.ThenAsync(string.Format("the element \"result-status\" has attribute \"{0}\" equal to \"{1}\"", attribute, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-09 — Result status notification label matches i18n key on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-09 — Result status notification label matches i18n key on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-C09")]
        public async global::System.Threading.Tasks.Task VRE_09ResultStatusNotificationLabelMatchesI18NKeyOnErrorPath()
        {
            string[] tagsOfScenario = new string[] {
                    "VRE-C09"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-09 — Result status notification label matches i18n key on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 154
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 155
      await testRunner.ThenAsync("the element \"result-status\" has attribute \"label\" equal to i18n key \"verification" +
                        "Result.error.title\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Error-path button is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Error-path button is visible")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-D10")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10", "show-report-btn", "28", null, DisplayName="VRE-<tag> — Error-path button is visible(10,show-report-btn,28)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("11", "ok-btn", "29", null, DisplayName="VRE-<tag> — Error-path button is visible(11,ok-btn,29)")]
        public async global::System.Threading.Tasks.Task VRE_TagError_PathButtonIsVisible(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-D10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Error-path button is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 160
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 161
      await testRunner.ThenAsync(string.Format("the element \"{0}\" is visible", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Error-path button has the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Error-path button has the correct color")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-D12")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("12", "show-report-btn", "secondary", "30", null, DisplayName="VRE-<tag> — Error-path button has the correct color(12,show-report-btn,secondary," +
            "30)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("13", "ok-btn", "primary", "31", null, DisplayName="VRE-<tag> — Error-path button has the correct color(13,ok-btn,primary,31)")]
        public async global::System.Threading.Tasks.Task VRE_TagError_PathButtonHasTheCorrectColor(string tag, string element, string color, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-D12"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("color", color);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Error-path button has the correct color", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 169
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 170
      await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"color\" equal to \"{1}\"", element, color), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Error-path button has the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Error-path button has the correct label")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-D14")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("14", "show-report-btn", "verificationResult.error.showReport", "32", null, DisplayName="VRE-<tag> — Error-path button has the correct label(14,show-report-btn,verificati" +
            "onResult.error.showReport,32)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("15", "ok-btn", "common.ok", "33", null, DisplayName="VRE-<tag> — Error-path button has the correct label(15,ok-btn,common.ok,33)")]
        public async global::System.Threading.Tasks.Task VRE_TagError_PathButtonHasTheCorrectLabel(string tag, string element, string key, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-D14"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            argumentsOfScenario.Add("key", key);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Error-path button has the correct label", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 178
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 179
      await testRunner.ThenAsync(string.Format("the element \"{0}\" has attribute \"label\" equal to i18n key \"{1}\"", element, key), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-<tag> — Success-path button is not present on the error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-<tag> — Success-path button is not present on the error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-E16")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("16", "cancel-btn", "34", null, DisplayName="VRE-<tag> — Success-path button is not present on the error path(16,cancel-btn,34" +
            ")")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("17", "proceed-install-btn", "35", null, DisplayName="VRE-<tag> — Success-path button is not present on the error path(17,proceed-insta" +
            "ll-btn,35)")]
        public async global::System.Threading.Tasks.Task VRE_TagSuccess_PathButtonIsNotPresentOnTheErrorPath(string tag, string element, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VRE-E16"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tag", tag);
            argumentsOfScenario.Add("element", element);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-<tag> — Success-path button is not present on the error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 189
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 190
      await testRunner.ThenAsync(string.Format("the element \"{0}\" is not present", element), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("VRE-18 — Info-bar hint displays the correct text on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("VRE-18 — Info-bar hint displays the correct text on error path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Verification Result")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("VRE-F18")]
        public async global::System.Threading.Tasks.Task VRE_18Info_BarHintDisplaysTheCorrectTextOnErrorPath()
        {
            string[] tagsOfScenario = new string[] {
                    "VRE-F18"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "36";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VRE-18 — Info-bar hint displays the correct text on error path", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("When the backend reports Not Ok the error layout is rendered", null, tagsOfRule);
#line 200
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 117
      await testRunner.GivenAsync("the app is running and the verification result screen is visible with an error re" +
                        "sult", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
      await testRunner.ThenAsync("the element \"verification-result-info-bar-hint\" has attribute \"label\" equal to i1" +
                        "8n key \"verificationResult.error.info\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
